name: Go

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install cross-build dependencies
      run: sudo apt-get -qq -y update && sudo apt-get -qq -y --no-install-recommends install make gcc gcc-multilib gcc-mingw-w64 autoconf automake libtool pkg-config ca-certificates wget patch sed git-core moreutils zip

    - name: Show info about build environment
      run: |
        cat /etc/debian_version
        go version
        gcc --version
        x86_64-w64-mingw32-gcc --version

    - name: Build 3rd-party deps
      run: make 3rdparty-all && make unit-test

    - name: Build
      run: make release VERSIONSUFFIX=+$GITHUB_SHA

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: spyre-zips
        path: spyre-*.zip

  build-macosx:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2

    - name: Update build environment
      run: |
        brew update

    - name: Install build-dependencies
      run: |
        brew install \
            make autoconf automake libtool pkg-config wget patchutils \
            gnu-sed gnu-tar ca-certificates zip

    - name: Build 3rd-party deps
      run: |
        gmake 3rdparty-all
        gmake unit-test
        find -name 'yara.pc*'

    - name: Build
      run: gmake release VERSIONSUFFIX=+$GITHUB_SHA

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: spyre-macosx-zips
        path: spyre-*.zip
