name: Go

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install cross-build dependencies
      run: sudo apt-get -q -y update && sudo apt-get -q -y --no-install-recommends install make gcc gcc-multilib gcc-mingw-w64 autoconf automake libtool pkg-config ca-certificates wget patch sed git-core moreutils zip

    - name: Build 3rd-party deps
      run: make 3rdparty-all && make unit-test

    - name: Build
      run: make release VERSIONSUFFIX=$GITHUB_SHA

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: spyre-zips
        path: spyre-*.zip
